[package]
name = "auto-reexport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_metadata = "0.14"
rustdoc-types = "0.11"
rustfix = "0.6"
serde_json = "1.0"

